### PR TITLE
Add --debug and --region options

### PR DESCRIPTION
**Pull request by pbrisbin**
/cc @codeclimate/review

### CODE REVIEW

**Comment by jpignata** [comment]
I don't think region makes sense in the context of the APIs popeye calls. It appears to be a no-op. See: http://docs.aws.amazon.com/general/latest/gr/rande.html

> Some services, such as IAM, do not support regions; therefore, their endpoints do not include a region.

**Comment by pbrisbin** [comment]
You're right. I realized this shortly after and plan to take that out.

**Comment by pbrisbin** [comment]
@jpignata Removed.

**Comment by jpignata** [comment]
Looks like Haskell to me.

**Comment by pbrisbin** [comment]
@jpignata FWIW, this is a pretty good example diff to come back and try to figure out after we read the Functor and Applicative chapters in Maybe Haskell.

**Pull request merged**
