### PR TITLE
Two-stage build

### PR DESCRIPTION
**Pull request by pbrisbin**
/cc @wfleming

### CODE REVIEW

**Comment by pbrisbin** [comment]
@wfleming I got this working. It required using `debian:jessie` (not alpine) which is the same base image as the build image. Still, the resulting image is about 100MB, much better than the 1.2GB build image.

**Comment by wfleming** [comment]
\0/

**Comment by pbrisbin** [comment]
Minor complication: The DockerHub automated build won't work now. We'll have to replace it with a normal repository and do our own push. Sigh.

**Comment by wfleming** [comment]
> Minor complication: the DockerHub automated build won't work now. We'll have to replace it with a normal repository and do our own push. Sigh.

Didn't realize we were using the DockerHub automated build. Oh well. We can do a Circle build like some other tools, can't we?

**Comment by pbrisbin** [comment]
That, or let shipbot do it.

**Comment by pbrisbin** [comment]
We could also commit the `build/popeye` executable to the repository. Then the normal `Dockerfile` would build fine on DockerHub...

**Comment by pbrisbin** [comment]
@wfleming I actually think committing the binary is the simplest approach here, WDYT?

**Comment by wfleming** [comment]
I'm a bit conflicted about that: it means you have to remember to run that build locally, which significantly reduces the usefulness of the CI setup. I'm fine with it over the CI setup if you think it's easier. Might be worth noting in the README/CONTRIBUTING file or something.

**Comment by pbrisbin** [comment]
OK, I've added the `circle.yml` changes to push to DockerHub. Do we have a dedicated user I whose credentials I can put in the build environment?

**Comment by pbrisbin** [comment]
It appears you can push to an Automated Build, so I don't need to delete recreate, I've just disabled the automated-ness. I've also added the shipbot variables to Circle, so I think this is ready to merge and see what happens.

**Comment by wfleming** [comment]
:+1:

**Pull request merged**
